version: '3.9'

services:

    # MariaDB(MySQL) для основного хранения данных
    mariadb:
        image: mariadb:latest
        container_name: vanillacrm_mariadb
        restart: on-failure:3
        env_file:
            - ./.env
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - "3306:3306"


    # PhpMyAdmin для управления MariaDB
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: vanillacrm_phpmyadmin
        restart: on-failure:3
        env_file:
            - ./.env
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - mariadb


    # PHP-FPM для VanillaCRM
    vanillacrm_src:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: vanillacrm_src
        restart: on-failure:3
        env_file:
            - ./.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./:/var/www/vanillacrm_src
            - ./.env:/var/www/vanillacrm_src/.env
            - ./wait-for-it.sh:/wait-for-it.sh:ro
        depends_on:
            - mariadb

    # Nginx как реверс-прокси для VanillaCRM
    nginx:
        image: nginx:latest
        container_name: vanillacrm_nginx
        restart: on-failure:3
        ports:
            - "8002:80"   # VanillaCRM
        volumes:
            - ./:/var/www/vanillacrm_src:ro
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - vanillacrm_src

volumes:
    mariadb_data:
