services:
    db:
        image: mariadb:latest
        container_name: mariadb_vanillacrm
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vanillacrm
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin_vanillacrm
        environment:
            PMA_HOST: mariadb
            PMA_USER: user
            PMA_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"

volumes:
    db_data:
